name: "harboor-auth"

services:
    clickhouse:
        image: clickhouse:25.3.2
        hostname: clickhouse
        ulimits:
            nofile:
                soft: 262144
                hard: 262144
        cap_add:
            - SYS_NICE
            - NET_ADMIN
            - IPC_LOCK
        restart: unless-stopped
        volumes:
            - clickhouse_data:/var/lib/clickhouse/
            - clickhouse_logs:/var/log/clickhouse-server/
        environment:
            CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
            CLICKHOUSE_DB: ${CLICKHOUSE_DB}
            CLICKHOUSE_USER: ${CLICKHOUSE_USER}
            CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD}
        healthcheck:
            test: ["CMD", "wget", "--spider", "-q", "localhost:8123/ping"]
            interval: 30s
            timeout: 10s
            retries: 5

    rabbitmq:
        image: rabbitmq:4-alpine
        hostname: harboor
        environment:
            RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_VHOST}
            RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
            RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
            RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE}
        volumes:
            - rabbitmq_data:/var/lib/rabbitmq
        healthcheck:
            test: rabbitmq-diagnostics check_port_connectivity
            interval: 30s
            timeout: 10s
            retries: 5
            start_period: 10s
        restart: unless-stopped

    postgres:
        image: postgres:17.3-alpine3.21
        shm_size: 128mb
        volumes:
            - postgres_data:/var/lib/postgresql/data
        user: postgres
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_INITDB_ARGS: "--locale-provider=icu --icu-locale=tr-TR"
            LANG: tr_TR.utf8
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready" ]
            interval: 30s
            timeout: 20s
            retries: 5
        restart: unless-stopped

    redis:
        image: redis:7.4.2-alpine3.21
        volumes:
            - redis_data:/data
        environment:
            - REDIS_PASSWORD
        command: redis-server --requirepass ${REDIS_PASSWORD} --save 60 1 --loglevel warning
        healthcheck:
            test: ['CMD', 'redis-cli', 'ping']
            interval: 30s
            timeout: 20s
            retries: 5
        restart: unless-stopped

volumes:
    rabbitmq_data:
    postgres_data:
    redis_data:
    node_modules:
    clickhouse_data:
    clickhouse_logs:

networks:
    default:
        name: harboor
        external: true